package dao;

import app.ViewManager;
import hospital.Patient;
import javafx.collections.ListChangeListener;

/**
 * The PatientChangeListener class is a listener for use with PatientCollection.
 * It passes the changes off to the PatientDao for processing.
 *
 * If you want to change the storage method we use in the app change the dao
 * type in the constructor.
 *
 * Usage:
 *
 * Attach it to the patient list object. This should be done in the main
 * controller based on our architecture, but it can be used by any controller.
 * It should always be attached before objects are added to the list.
 *
 * This implementation works because the PatientCollection model must contain an
 * ObservableList for use with a JavaFX table view. We can take advantage of the
 * existing list by adding this change listener, which responds to events
 * generated by the list. This approach removes the need for models to call the
 * dao or controllers when making internal changes in order to save data.
 *
 * @see ViewManager
 * @see PatientDao
 *
 * @author redjen
 *
 */
public class PatientChangeListener implements ListChangeListener<Patient> {

   private final PatientDao dao;

   /**
    * Constructs a new PatientChangeListener and hooks it up to a patientDao for
    * reading and writing patient data.
    *
    * @throws DaoException
    */
   public PatientChangeListener() throws DaoException {
      this.dao = DaoFactory.getPatientDao();
   }

   /**
    * Change handler for the observed list. It calls the PatientDAO to update
    * the data stored on disk.
    *
    * We only care about adding, updating, and deleting patients. The order of
    * objects within PatientCollection doesn't matter so the getPermuted event
    * should be ignored.
    *
    * @param changes a Change object containing lists of changes and a reference
    * to the ObservableList
    */
   @Override
   public void onChanged(Change<? extends Patient> changes) {
      while (changes.next()) {

         // new patient created
         if (changes.wasAdded()) {
            for (Patient patient : changes.getAddedSubList()) {
               dao.savePatient(patient);
            }
         }

         // updates to patient attributes
         if (changes.wasUpdated()) {
            for (int i = changes.getFrom(); i < changes.getTo(); i++) {
               dao.savePatient(changes.getList().get(i));
            }
            System.out.println(changes.getFrom() + " to " + changes.getTo());
         }

         // patient deleted (to be archived)
         if (changes.wasRemoved()) {
            for (Patient patient : changes.getRemoved()) {
               dao.archivePatient(patient);
            }
         }
      }
   }

}
